#!/bin/bash

# Settings needed for the Meteos plugin
# -------------------------------------

# Set up default directories
METEOSCLIENT_DIR=$DEST/python-meteosclient
METEOS_DIR=$DEST/meteos

METEOSCLIENT_REPO=${METEOSCLIENT_REPO:-\
${GIT_BASE}/openstack/python-meteosclient.git}
METEOSCLIENT_BRANCH=${METEOSCLIENT_BRANCH:-master}

METEOS_CONF_DIR=${METEOS_CONF_DIR:-/etc/meteos}
METEOS_CONF_FILE=${METEOS_CONF_DIR}/meteos.conf

# TODO(slukjanov): Should we append meteos to SSL_ENABLED_SERVICES?

if is_ssl_enabled_service "meteos" || is_service_enabled tls-proxy; then
    METEOS_SERVICE_PROTOCOL="https"
fi
METEOS_SERVICE_HOST=${METEOS_SERVICE_HOST:-$SERVICE_HOST}
METEOS_SERVICE_PORT=${METEOS_SERVICE_PORT:-8989}
METEOS_SERVICE_PROTOCOL=${METEOS_SERVICE_PROTOCOL:-$SERVICE_PROTOCOL}
METEOS_ENDPOINT_TYPE=${METEOS_ENDPOINT_TYPE:-adminURL}

METEOS_AUTH_CACHE_DIR=${METEOS_AUTH_CACHE_DIR:-/var/cache/meteos}

METEOS_BIN_DIR=$(get_python_exec_prefix)

METEOS_ENABLE_DISTRIBUTED_PERIODICS=${METEOS_ENABLE_DISTRIBUTED_PERIODICS:-\
True}

enable_service meteos-api meteos-eng
